apiVersion: v1
entries:
  prowler:
  - annotations:
      artifacthub.io/alternativeName: prowler-app
      artifacthub.io/category: security
      artifacthub.io/changes: |
        - kind: fixed
          description: Worker services startup command
        - kind: changed
          description: Environment variables setup for API and worker services
          links:
            - name: Github PR
              url: https://github.com/promptlylabs/prowler-helm-chart/pull/2
      artifacthub.io/links: |
        - name: source
          url: https://github.com/guilhermealegre/prowler-helm-chart
        - name: application source
          url: https://github.com/prowler-cloud/prowler
        - name: support
          url: https://github.com/promptlylabs/prowler-helm-chart/issues
      artifacthub.io/screenshots: |
        - title: Sign In
          url: https://promptlylabs.github.io/prowler-helm-chart/docs/images/sign_in.png
    apiVersion: v2
    appVersion: 5.5.1
    created: "2025-11-14T22:39:49.638758Z"
    description: Prowler is an Open Cloud Security tool for AWS, Azure, GCP and Kubernetes.
      It helps for continuous monitoring, security assessments and audits, incident
      response, compliance, hardening and forensics readiness.
    digest: 5b3b2dcc53241745b87f6f6a21f01d0cef85fee647650c30402d8aadb768b4ec
    home: https://prowler.com/
    icon: https://prowler.com/wp-content/themes/prowler-2024/img/web-logo-prowler-p.png
    keywords:
    - security
    - aws
    - azure
    - gcp
    - kubernetes
    maintainers:
    - email: guilherme93alegre@promptlyhealth.com
      name: guilhermealegre
    name: prowler
    type: application
    urls:
    - https://guilhermealegre.github.io/prowler-helm-chart/prowler-0.0.2.tgz
    version: 0.0.2
generated: "2025-11-14T22:39:49.637456Z"
